######################## default configuration ####################
baseURL = "https://zabel.biz"
title = "Zabel Objektbetreuung"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/css/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/css/hover-min.css"
[[params.plugins.css]]
link = "plugins/css/dm_sans.css"
[[params.plugins.css]]
link = "plugins/css/text-animation.css"
[[params.plugins.css]]
link = "plugins/css/hugrid.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/js/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "plugins/js/jquery.waypoints.js"
[[params.plugins.js]]
link = "plugins/js/text-animation.js"
[[params.plugins.js]]
link = "plugins/js/hugrid.min.js"
[[params.plugins.js]]
link = "plugins/js/safe-email.min.js"
[[params.plugins.js]]
link = "plugins/js/safe-number.min.js"

############################## navigation ###############################

[[menu.main]]
name = "Home"
URL = "/#"
weight = 1

[[menu.main]]
name = "Unternehmen"
URL = "/#unternehmen"
weight = 2

[[menu.main]]
name = "Dienstleistungen"
URL = "/#dienstleistungen"
weight = 3

[[menu.main]]
name = "Kontakt"
URL = "/#kontakt"
weight = 4

[[menu.main]]
name = "Impressum"
URL = "/impressum"
weight = 5

[[menu.main]]
name = "Datenschutz"
URL = "/datenschutz"
weight = 6

#################### default parameters ################################
[params]
copyright = "Copyright Lennox Zabel &copy;"
# Meta data
description = "Zabel Objektbetreuung"
author = "Lennox Zabel"
favicon = "images/icon.png"
logo_light = "images/logo-light.svg"
logo_dark = "images/logo-dark.svg"

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

[markup.goldmark.renderer]
unsafe = true
